web:
  build: ./
  ports:
  - "8090:80"
  volumes:
  - /home/tiago/web/:/var/www/html/
  container_name: php7
  links:
  - mysql

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./dumps/:/var/lib/opt/dumps
  container_name: mysql

  
